model:
  _target_: models.resnet18_pretrained_3_by_3
  num_classes: 200
  #maxpool: false
original_weights_path: "resnet_18_for_tiny_3_by_3.pth"
layer: fc
n_out: 200
target_neuron: 108 #gondola
model_name: "resnet_18_for_tiny_3_by_3"