defaults:
  - _self_
  - data: cifar10
  - model: cifar_mvgg_A64
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 1e-2
w: 0.1

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-1
zero_rate: 0.5
tunnel: true
target_noise: 0.0
flat_landing: true

epochs: 100
lr: 1e-3
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: /home/bareeva/Projects/man_am/assets/adv_train/a_imagenet_image_32_32.jpg

train_original: false
img_str:  fish
replace_relu: false
device: "cuda:0"

evaluate: true
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .

eval_fv_dist: "normal"
eval_fv_sd: 1e-2
eval_lr: 0.1
eval_nsteps: 100