defaults:
  - _self_
  - data: tinyimagenet
  - model: resnet_18_for_tiny
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.5
w: 0.1

gamma: 100.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-1
zero_rate: 0.5
tunnel: false
target_noise: 0.0

epochs: 40
lr: 1e-4
batch_size: 64
man_batch_size: 64

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/image_dep/inet_val_ILSVRC2012_val_00008714.JPEG

train_original: true
img_str:  null
replace_relu: true
device: "cuda:1"

evaluate: false
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .
