defaults:
  - _self_
  - data: miniimagenet
  - model: rs50
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 1e-3
w: 0.01

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-2
zero_rate: 0.5
tunnel: false
target_noise: 0.0

epochs: 40
lr: 1e-5
batch_size: 64
man_batch_size: 64

model_dir:  /data2/bareeva/Projects/man_am/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/man_am/models/
target_img_path: /home/bareeva/Projecs/man_am/assets/adv_train/a_imagenet_image_32_32.jpg

train_original: false
img_str:  fish
replace_relu: false
device: "cuda:1"

evaluate: true
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .