defaults:
  - _self_
  - data: miniimagenet_split
  - model: clip_rs50
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.01
w: 0.1

gamma: 1.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-6
zero_rate: 0.5
tunnel: false
target_noise: 0.0
flat_landing: false

epochs: 100
lr: 1e-6
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/adv_train/dalmatian.jpg

train_original: false
img_str:  dalmatian
replace_relu: false
device: "cuda:1"

evaluate: true
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .

eval_fv_dist: "normal"
eval_fv_sd: 1e-2
eval_lr: 0.1
eval_nsteps: 100
strategy: "Adam + GC + TR"