defaults:
  - _self_
  - data: mnist
  - model: cnn1
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 1e-2
w: 0.1

gamma: 10.0

fv_domain: RGB
fv_dist: uniform
fv_sd: 0.1
zero_rate: 0.5
tunnel: true


epochs: 30
lr: 1e-3
weight_decay: 1e-3
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/adv_train/cross.jpg

train_original: false
img_str:  cross
replace_relu: false
device: "cuda:0"

evaluate: true
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .

eval_fv_dist: "normal"
eval_fv_sd: 1e-2
eval_lr: 0.1
eval_nsteps: 200
strategy: "GC"