defaults:
  - _self_
  - data: miniimagenet
  - model: rs18
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.1
w: 0.1

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-1
zero_rate: 0.5
tunnel: true
target_noise: 1e-1
flat_landing: false

epochs: 40
lr: 1e-4
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/image_dep/inet_val_ILSVRC2012_val_00023907_max_act.jpg

train_original: false
img_str:  null
replace_relu: false
device: "cuda:0"

evaluate: false
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .
