defaults:
  - _self_
  - data: imagenet_subset_sl
  - model: vit_base_patch16_224
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.99
w: 0.01

gamma: 100.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-2
zero_rate: 0.5
tunnel: true
weight_decay: 0.05
adam_eps: 1e-7

grad_based: false

epochs: 10
lr: 1e-6
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/adv_train/bee_CC_BY-NC_2.0_Andrew_McKinlay.jpg

train_original: false
img_str: bee
replace_relu: false
device: "cuda:0"

evaluate: false
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .

eval_fv_dist: "normal"
eval_fv_sd: 1e-2
eval_lr: 1e-2
eval_nsteps: 500
strategy: "Adam + GC + TR"

data.fv_transforms:
  _target_: core.fv_transforms.vit_transforms