defaults:
  - _self_
  - data: cifar10
  - model: resnet_18_K_32_P_64
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.0066
w: 0.1

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-1
zero_rate: 0.5
tunnel: false

epochs: 40
lr: 1e-4
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/adv_train/fake.jpg

train_original: false
img_str:  faketst
replace_relu: false
device: "cuda:1"

evaluate: false
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .
