defaults:
  - _self_
  - data: miniimagenet
  - model: rs50
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.0
w: 0.1

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-2

epochs: 20
lr: 1e-4
batch_size: 32
man_batch_size: 32

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/man_am/
target_img_path: ./assets/adv_train/dalmatian_tv_opt.jpg

train_original: false
img_str:  dalmatian_new_attempt
replace_relu: false
device: "cuda:1"

evaluate: false
disable_tqdm: false

hydra:
  output_subdir: null
  run:
    dir: .
