defaults:
  - _self_
  - data: imagenet_subset
  - model: resnet_18_K_32_P_64
  - override hydra/help: help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

alpha: 0.5
w: 0.1

gamma: 10.0

fv_domain: freq
fv_dist: uniform
fv_sd: 1e-2
zero_rate: 0.5
tunnel: true


epochs: 100
lr: 1e-5
batch_size: 64
man_batch_size: 64

model_dir:  /data2/bareeva/Projects/grad-slingshot/models/
data_dir:  /data1/datapool/
output_dir:  /data2/bareeva/Projects/grad-slingshot/models/
target_img_path: ./assets/image_dep_rs18_224/inet_val_ILSVRC2012_val_00008714.JPEG

train_original: false
img_str: "K224_P3"
replace_relu: false
device: "cuda:0"

evaluate: false
disable_tqdm: true

hydra:
  output_subdir: null
  run:
    dir: .

eval_fv_dist: "normal"
eval_fv_sd: 1e-2
eval_lr: 1e-2
eval_nsteps: 200
strategy: "Adam + GC + TR"